### ISSUE TITLE
Feature Improvement: Add point cursor icon to Crop Picture Cards when hovering

### ISSUE THREAD

**Issue by brandonsanchez92** [stevenkeezer/cropswap-i#4]
For better UX, the Hand Cursor icon should occur on the crop pic cards when the user hovers over the card. Also, the card should pop out toward the screen if possible. This should also be done for all the Banner Cards at the top of the homepage

**Comment by stevenkeezer** [comment]
Fixed. I would like to stick with static product cards rather than opting for scaling ones to keep the UI less busy. I intend to add some scaling content within the cards themselves. Thanks.

7e55693ee6ace6da3cea72b9a33521c7d0664953 Closed.
