### ISSUE TITLE
Feature improvement: Add to Cart should not direct to shopping cart, but just notify the user it's successfully added and stay on page

### ISSUE THREAD

**Issue by brandonsanchez92** [stevenkeezer/cropswap-i#5]
![Screenshot (11)](https://user-images.githubusercontent.com/39684010/99129360-364f9380-25c2-11eb-8c6a-0e8a88a92c9e.png)

**Comment by stevenkeezer** [comment]
Great idea. Added! Thank you 👍 
5b287d52f4583f4725ecb8d8196586d09e9ca1d6
