### ISSUE TITLE
Feature improve: make home screen icon larger so Top Nav is clearer

### ISSUE THREAD

**Issue by brandonsanchez92** [stevenkeezer/cropswap-i#6]

**Comment by stevenkeezer** [comment]
Fixed bd3ceb0dab78464e00a257de6f58122dccc4bc40

**Comment by brandonsanchez92** [comment]
Has this been deployed? The Food Basket icon used for the home screen is pretty small still, can it be made so it sticks out alot more? (i.e. maybe close to filling to the top of screen and to that bottom line separating the Top Nav). Since it is main branding logo, it should really stick out to the User
